apiVersion: apps/v1
kind: Deployment
metadata:
  name: cameron-stedi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cameron-stedi
  template:
    metadata:
      labels:
        app: cameron-stedi
    spec:
      containers:
        - name: cameron-stedi
          image: gcr.io/teca-350016/stedi-cameron:latest
          command: ["npm"]
          args: ["run", "start"]
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: ".5"
              memory: "500Mi"
            requests:
              cpu: ".25"
              memory: "250Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 3

---

apiVersion: v1
kind: Service
metadata:
  name: cameron-stedi-loadbalancer
spec:
  selector:
    app: cameron-stedi
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000